Lucasweb/Controllers/SharedController.cs
using Lucasweb.Contracts;
using Lucasweb.DataContracts;
using Lucasweb.Models;
using Lucasweb.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Lucasweb.Controllers
{
    public class SharedController : Controller
    {
        private UserIdentityManager _appIdManager;

        private IdentityContext AUIdb = new IdentityContext();

        public UserIdentityManager AppIdManager
        {
            get
            {
                return _appIdManager ?? HttpContext.GetOwinContext().GetUserManager<UserIdentityManager>();
            }
            private set
            {
                _appIdManager = value;
            }
        }


        private IUserManager _userDataManager;

        public IUserManager UserDataManager
        {
            get
            {
                return (_userDataManager ?? ClassFactory.CreateClass<IUserManager>());
            }
        }


        [ActionName("_DropDownStuff")]
        public PartialViewResult _DropDownStuff()
        {
            AppUserId AUI = AppIdManager.FindById(User.Identity.GetUserId());
            if (AUI == null)
            {
                return PartialView();
            }
            else
            {
                User UserData = UserDataManager.GetUser(AUI.UserId);
                return PartialView(UserData);
            }

        }
    }
}

Lucasweb/Views/Shared/_DropDownStuff.cshtml
@model Lucasweb.DataContracts.User
    <style>
        .container-fluid{
            padding-right:0;
        }

    </style>
<div class="ZI-2">
    <h4 class="text-center">Account</h4>
    @if (Model == null)
    {
        <p class="text-default text-center">Welcome, Guest</p>
        <div class="container-fluid">
            <div class="row">
                <a class="btn btn-success col-xs-12 col-md-6" href="~/Account/Register" role="button">Register</a>
                <a class="btn btn-info col-xs-12 col-md-6" href="~/Account/Login" role="button">Sign In</a>
            </div>
        </div>

    }
    else
    {
        <p class="text-default text-center">Welcome, @Model.UserName</p>
        <div class="container-fluid">
            <div class="row">
                <a class="btn btn-primary col-xs-12 col-md-6" href="~/Account/" role="button">My Account</a>
                <a class="btn btn-danger col-xs-12 col-md-6" href="~/Account/Logout" role="button">Sign Out</a>
            </div>
        </div>

    }



</div>

Lucasweb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en-us">
<head>
    <meta name="viewport" content="width=device-width" />
    @Html.Raw("<title>" + ViewBag.Title + " - Lucasweb </title>")
    <link rel="stylesheet" href="~/Content/bootstrap-3.3.6-dist/css/bootstrap.css"/>
    <link rel="stylesheet" href="~/Content/Site.css"/>
    @*<link rel="stylesheet/less" type="text/css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/less.js/2.7.1/less.min.js" type="text/javascript"></script>*@
    <link rel="icon" href="~/Content/NiceIcon.png"/>
    <script src="~/scripts/jquery-1.10.2.min.js"></script>
    <script>
        function settingPopup() {
            document.getElementById("settings-dropdown-stuff").classList.toggle("show");
            popupMargin();
        }

        // Close the dropdown menu if the user clicks outside of it
        window.onclick = function (event) {
            if (!event.target.matches('.dropbtn')) {

                var dropdowns = document.getElementsByClassName("dropdown-content");
                var i;
                for (i = 0; i < dropdowns.length; i++) {
                    var openDropdown = dropdowns[i];
                    if (openDropdown.classList.contains('show')) {
                        openDropdown.classList.remove('show');
                    }
                }
            }
        }
        function popupMargin() {
            var sds = $("#settings-dropdown-stuff");
            sds.css("margin-left",$("#headbar").width()-sds.width());
        }
        window.onresize = popupMargin;
    </script>
    <style>
        .row {
            margin-right: 0;
        }

        .container {
            margin-right: 0;
            margin-left: 0;
        }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <div id="headbar" class="row Mstrip B-555">
        <div class="Pstrip col-lg-1 col-xs-2">
            <a href="~/" class="H0-75in">
                <div class="row Mstrip">
                    <img class="H0-75in" id="lucaslogo" src="~/Content/ProfileImage.png" alt="Home Icon"/>
                </div>
            </a>
        </div>
        <div id="setting-dropdown">
            <span onclick="settingPopup()" class="text-right glyphicon glyphicon-menu-down Font24px dropbtn" id="setting-icon"></span>
            <div id="settings-dropdown-stuff" class="dropdown-content ZI-2">
                @{Html.RenderAction("_DropDownStuff", "Shared", new { area = "" }); }
            </div>
        </div>

    </div>
    <div>
        @RenderBody()
    </div>
    <div class="B-555" id="footer">
        <div id="footerText" class="text-center">
            <p class="text-center" id="footerCopywrite">©2016 Lucasweb Productions, Herman, NE.  All rights reserved.  I think.</p>
            <small class="text-center">The Lucasweb:  A combination of epic coding fails.</small>
        </div>
    </div>
</body>
</html>